version: "3.7"

services:
  club_app: &app
    build:
      dockerfile: Dockerfile
      context: .
    command: make docker-run-production
    container_name: club_app
    environment:
      - MODE=production
      - PYTHONUNBUFFERED=1
      - DEBUG=false
      - APP_HOST=https://vyshka.club
      - MEDIA_UPLOAD_URL=https://i.vyshka.club/upload/
      - POSTGRES_DB=vyshka_club
      - POSTGRES_USER=vyshka
      - POSTGRES_PASSWORD=vyshka
      - POSTGRES_HOST=postgres
      - REDIS_DB=0
      - REDIS_HOST=redis
    restart: always
    volumes:
      - ./frontend:/app/frontend/
      - ./gdpr/downloads:/app/gdpr/downloads
    depends_on:
      - postgres
      - redis
      - queue
    ports:
      - "127.0.0.1:8814:8814"

  queue:
    <<: *app
    command: make docker-run-queue
    container_name: club_queue
    depends_on:
      - postgres
      - redis
    ports: []

  bot:
    <<: *app
    command: make docker-run-bot
    container_name: club_bot
    depends_on:
      - club_app
      - postgres
      - redis
    ports:
      - "8816:8816"

  cron:
    <<: *app
    command: make docker-run-cron
    container_name: club_cron
    depends_on:
      - club_app
      - postgres
      - redis
    ports: []

  postgres:
    image: postgres:12
    container_name: club_postgres
    restart: always
    environment:
      POSTGRES_USER: vyshka
      POSTGRES_PASSWORD: vyshka
      POSTGRES_DB: vyshka_club
    volumes:
      - /var/www/pgdata:/var/lib/postgresql/data:rw
    ports:
      - "127.0.0.1:54333:5432"

  redis:
    image: redis:alpine
    container_name: club_redis
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  pepic:
    build: ../i.vyshka.club
    container_name: pepic
    environment: # check out pepic/config/app.go for more env variables
      - BASE_URL=http://i.vyshka.club/
      - STORAGE_DIR=/uploads
      - SECRET_CODE=ths_is_a_secret
      - IMAGE_ORIGINAL_LENGTH=1400
      - MAX_UPLOAD_SIZE=100M
    volumes:
      - ../i.vyshka.club/uploads:/uploads
    ports:
      - 8118:8118
    user: "1000" # set your real uid (by default only root can read the uploaded files)
    restart: unless-stopped
