version: "3.7"
services:
  club_app: &app
    image: ghcr.io/m-fedosov/vyshka.club:${GITHUB_SHA:-latest}
    build:
      dockerfile: Dockerfile
      context: .
    command: make docker-run-production
    container_name: club_app
    environment:
      - MODE=production
      - PYTHONUNBUFFERED=1
      - DEBUG=false
      - APP_HOST=https://vyshka.club
      - MEDIA_UPLOAD_URL=https://media.vyshka.club/upload/
      - POSTGRES_DB=vyshka_club
      - POSTGRES_USER=vyshka
      - POSTGRES_PASSWORD=vyshka
      - POSTGRES_HOST=postgres
      - REDIS_DB=0
      - REDIS_HOST=redis
      - VIRTUAL_HOST=vyshka.club,www.vyshka.club
      - VIRTUAL_PORT=8814
      - VIRTUAL_PATH=/
    env_file:
      - club/.env
    restart: always
    volumes:
      - ./frontend/static:/tmp/static
      - ./gdpr/downloads:/app/gdpr/downloads
    depends_on:
      - postgres
      - redis
      - queue
    ports:
      - "127.0.0.1:8814:8814"
    networks:
      - front
      - club

  queue:
    <<: *app
    command: make docker-run-queue
    container_name: club_queue
    depends_on:
      - postgres
      - redis
    ports: []
    networks:
      - club

  bot:
    <<: *app
    command: make docker-run-bot
    container_name: club_bot
    environment:
      - APP_HOST=https://vyshka.club
      - POSTGRES_DB=vyshka_club
      - POSTGRES_USER=vyshka
      - POSTGRES_PASSWORD=vyshka
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - REDIS_DB=0
      - VIRTUAL_HOST=vyshka.club
      - VIRTUAL_PATH=/telegram/webhook/
      - VIRTUAL_PORT=8816
    depends_on:
      - club_app
      - postgres
      - redis
    ports:
      - "8816:8816"
    networks:
      - club

  cron:
    <<: *app
    command: make docker-run-cron
    container_name: club_cron
    depends_on:
      - club_app
      - postgres
      - redis
    ports: []

  postgres:
    image: postgres:12
    container_name: club_postgres
    restart: always
    environment:
      POSTGRES_USER: vyshka
      POSTGRES_PASSWORD: vyshka
      POSTGRES_DB: vyshka_club
    volumes:
      - /home/mike/pgdata:/var/lib/postgresql/data:rw
    ports:
      - "127.0.0.1:54333:5432"
    networks:
      - club

  redis:
    image: redis:alpine
    container_name: club_redis
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - club

  pgbackups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - /home/mike/backup/club/pgdata:/backups
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=vyshka_club
      - POSTGRES_USER=vyshka
      - POSTGRES_PASSWORD=vyshka
      - POSTGRES_EXTRA_OPTS=-Z6 --schema=public --blobs
      - SCHEDULE=@weekly
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=8080
    networks:
      - club

networks:
  front:
    name: vyshka_network
  club:
    name: club_network
